=== ahmed-zaheer/XSLT-HeapSort/heapdata.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="heap" type="max"/>
    <xs:complexType name="max">
        <xs:sequence>
            <xs:element ref="heap" minOccurs="0" maxOccurs="2"/>
        </xs:sequence>
        <xs:attributeGroup ref="node-attr"/>
        <xs:assert test="number(@value) &lt; number(../@value) or not(@output)"/>
    </xs:complexType>
    <xs:complexType name="min">
        <xs:sequence>
            <xs:element ref="heap" minOccurs="0" maxOccurs="2"/>
        </xs:sequence>
        <xs:attributeGroup ref="node-attr"/>
        <xs:assert test="number(@value) &gt; number(../@value) or not(@output)"/>
    </xs:complexType>
    <xs:attributeGroup name="node-attr">
        <xs:attribute name="index" type="xs:integer"/>
        <xs:attribute name="value" type="xs:integer"/>
    </xs:attributeGroup>
</xs:schema>

=== ahmed-zaheer/XSLT-HeapSort/heapdata.xml
<?xml version="1.0" encoding="UTF-8"?>
<heap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:math="http://exslt.org/math"
    xsi:noNamespaceSchemaLocation="heapdata.xsd"
    index="1"
    value="1">
    <heap index="2" value="7">
        <heap index="4" value="6">
            <heap index="8" value="4"/>
            <heap index="9" value="-1"/>
        </heap>
        <heap index="5" value="2"/>
    </heap>
    <heap index="3" value="3">
        <heap index="6" value="5"/>
        <heap index="7" value="0"/>
    </heap>
</heap>
